### PR TITLE
Fix Accepted Values for Importance Class

### LINKED ISSUE #102: Fix Behaviour to only allow certain values for Field

### PR DESCRIPTION
**Pull request by JuhromeAlexander**
Resolves #102

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Importance.java [hunk 1]
```diff
@@ -18,6 +18,8 @@ public class Importance {
      */
     public static final String VALIDATION_REGEX = "[^\\s].*";
 
+    private static final String[] VALID_IMPORTANCE_VALUES = {"low", "medium", "high"};
```
Comment (zephaniahong) [inline src/main/java/seedu/address/model/person/Importance.java:21]: Good that you are creating an array of valid values. Could consider using an ENUM?
