### PR TITLE
Fix Find functionality

### LINKED ISSUE #93: Fix Incorrect Logic with Command Format

### PR DESCRIPTION
**Pull request by JuhromeAlexander**
Resolves #93

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/FindCommand.java [hunk 1]
```diff
@@ -17,8 +17,10 @@ public class FindCommand extends Command {
 
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Finds all persons whose names contain any of "
             + "the specified keywords (case-insensitive) and displays them as a list with index numbers.\n"
-            + "Parameters: KEYWORD [MORE_KEYWORDS]...\n"
-            + "Example: " + COMMAND_WORD + " alice bob charlie";
+            + "Parameters: KEYWORD [MORE_KEYWORDS]... [c/COMPANY]\n"
+            + "Example: " + COMMAND_WORD + " alice whit c/Google\n"
+            + "Will only find all persons whose names start with alice whit that is from Google\n"
```
Comment (gn07) [inline src/main/java/seedu/address/logic/commands/FindCommand.java:22]: spelling error at this line "whit"
